### ISSUE TITLE
[Feature Request] Make secure by default/optional hardening 

### ISSUE THREAD

**Issue by dhauenstein** [khast3x/Redcloud#18]
Hi,
I would like to set up a redcloud instance, but would love to have an optional flag to make the web ui listen to localhost only (connecting to it via ssh fowarding) to eliminate the need to expose unwanted ports. I know this can be set in the config, but it would be nifty to have an optional flag for that.

**Comment by khast3x** [comment]
Hello,
Thank you for taking the time to explain what you had in mind.  
I see what you mean, but I don't think I'll be integrating this feature (sorry!).  

The elegant way of adding this feature is by using templates, but I don't think I want the project to become a templating tool.  
Furthermore, Redcloud is mainly for external deployment, avoiding cumbersome local download and storage of containers.  

**That being said**, if you wish to remove the web facing interfaces, you can do so by editing or removing mapped ports from the reverse proxy (traefik) in the `docker-compose.yml` file [here](https://github.com/khast3x/Redcloud/blob/master/docker-compose.yml#L18). You may also change the mapped port to something less obvious if you so wish.

Keep in mind Redcloud will pull Redcloud on the remote server by using git if it finds it on the installation candidate, otherwise it will copy the local files using `scp`. You can supress this behaviour in `redcloud.py`directly.  

Hope this helps,
Cheers

**Comment by dhauenstein** [comment]
Hey man, thanks for the detailed feedback. I totally understand it's not in your interest to bloat the code base unnecessary, no worries. 
Cheers and keep up the great work.
